### ISSUE TITLE
Save a command name with a context

### ISSUE THREAD

**Issue by calve** [calve/ase_plus_plus#3]
It would be cool to be able to name context, so we can show their name when `ps`.

We should 
- add a `name` field to the `ctx_s` struct
- change the prototype of `create_ctx(stack, func, params)` to `create_ctx(name, stack, func, params`
- change the existings calls to `create_ctx()` according to the new prototype
- change `do_ps()` to print the context name

**Comment by kfranquenouille** [comment]
It's a good idea and i will do that this week. With that, we could know easily to know what process is running on the core
